export const Genres: Map<number, string> = new Map();
Genres.set(28, 'Action')
Genres.set(12, 'Adeventure')
Genres.set(16, 'Animation')
Genres.set(35, 'Comedy')
Genres.set(80, 'Crime')
Genres.set(99, 'Documentary')
Genres.set(18, 'Drama')
Genres.set(10751, 'Family')
Genres.set(14, 'Fantasy')
Genres.set(36, 'History')
Genres.set(27, 'Horror')
Genres.set(10402, 'Music')
Genres.set(9648, 'Mystery')
Genres.set(10749, 'Romance')
Genres.set(878, 'Science Fiction')
Genres.set(10770, 'TV Movie')
Genres.set(53, 'Thriller')
Genres.set(10752, ' War')
Genres.set(37, 'Western')