name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: npm run test:headless
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
      with:
        angular_project_dir: ./watchlist-app
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        build_configuration: production
        base_href: https://hanover-cs.github.io/HC24-Dale-Donnelly-Senior-Project/
        deploy_branch: gh-pages
        angular_dist_build_folder: watchlist-app/dist/watchlist-app

permissions:
  contents: write