name: Test
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js latest
      uses: actions/setup-node@v3
      with:
        node-version: latest
    - name: Install dependencies
      run: cd watchlist-app && npm install
    - name: lint
      run: npm run lint
    - name: Test
      run: npm run test:headless